clc; clear; close all; 
bitRate = 1; 
Fs = 100; 
Tb = 1/bitRate; 
t = 0:1/Fs:Tb-1/Fs; 
msgBits = [1 0 1 1 0 0 1 0]; 
bitLength = length(msgBits); 
messageSignal = repelem(msgBits, length(t)); 
tTotal = 0:1/Fs:bitLength*Tb-1/Fs;  
fc = 10; 
fc1 = 3; 
fc2 = 7; 
carrier = cos(2*pi*fc*tTotal); 
ASKmod = messageSignal .* carrier; 
FSKmod = cos(2*pi*(fc1 + (fc2-fc1)*messageSignal).*tTotal); 
FSKdemod = zeros(1, bitLength); 
for i = 1:bitLength 
tSegment = (i-1)*length(t) + (1:length(t)); 
receivedBit1 = sum(FSKmod(tSegment) .* cos(2*pi*fc2*t)); 
receivedBit0 = sum(FSKmod(tSegment) .* cos(2*pi*fc1*t)); 
if receivedBit1 > receivedBit0 
FSKdemod(i) = 1; 
else 
FSKdemod(i) = 0; 
end 
end 
figure; 
subplot(3,1,1); 
stairs(msgBits, 'LineWidth', 2); 
ylim([-0.2 1.2]); 
title('ASK - Input Message Signal'); 
grid on; 
subplot(3,1,2); 
plot(tTotal, ASKmod, 'r'); 
title('ASK - Modulated Signal'); 
grid on; 
subplot(3,1,3); 
stairs(messageSignal(1:Fs:end), 'g', 'LineWidth', 2); 
ylim([-0.2 1.2]); 
title('ASK - Demodulated Signal'); 
grid on; 
shortMsgBits = [1 0 1 1 0]; 
shortBitLength = length(shortMsgBits); 
shortMessageSignal = repelem(shortMsgBits, length(t)); 
shortTTotal = 0:1/Fs:shortBitLength*Tb-1/Fs; 
BPSKmod = cos(2*pi*fc*shortTTotal + pi*(1 - shortMessageSignal)); 
figure; 
subplot(3,1,1); 
stairs(shortMsgBits, 'LineWidth', 2); 
ylim([-0.2 1.2]); 
title('BPSK - Input Message Signal'); 
grid on; 
subplot(3,1,2); 
plot(shortTTotal, BPSKmod, 'r'); 
title('BPSK - Modulated Signal'); 
grid on; 
subplot(3,1,3); 
recoveredBits = BPSKmod > 0; 
stairs(recoveredBits, 'g', 'LineWidth', 2); 
ylim([-0.2 1.2]); 
title('BPSK - Demodulated Signal'); 
grid on; 
figure; 
subplot(3,1,1); 
stairs(msgBits, 'LineWidth', 2); 
ylim([-0.2 1.2]); 
title('FSK - Input Message Signal'); 
grid on; 
subplot(3,1,2); 
plot(tTotal, FSKmod, 'r'); 
title('FSK - Modulated Signal'); 
grid on; 
subplot(3,1,3); 
stairs(FSKdemod, 'g', 'LineWidth', 2); 
ylim([-0.2 1.2]); 
title('FSK - Demodulated Signal'); 
grid on; 